name: 'Cypress Tests'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* 09 * * 1,3'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
         start: yarn start
         wait-on: 'https://mcp.gds.amalitech-dev.net'
         wait-on-timeout: 120
         record: true
         parallel: true
         spec: cypress/e2e/*
        env:
         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

